apiVersion: apps/v1
kind: Deployment
metadata:
  name: "goserver"
  labels: 
    app: "goserver"
spec:
  selector:
    matchLabels:
      app: "goserver"
  replicas: 2
  template:
    metadata:
      labels: 
        app: "goserver"
    spec:
      containers:
        - name: "goserver"
          image: "mikhathet/hello-go:v5.1"
          livenessProbe: 
            httpGet:
              path: /healthz
              port: 80
            periodSeconds: 5
            failureThreshold: 1
            timeoutSeconds: 1
            successThreshold: 1
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: 80
            periodSeconds: 3
            failureThreshold: 1
            # initialDelaySeconds: 15
          startupProbe:
            httpGet:
              path: /healthz
              port: 80
            periodSeconds: 3
            failureThreshold: 30
