apiVersion: v1
kind: Service
metadata:
  name: goserver-service
spec:
  selector:
    app: goserver 
  type: LoadBalancer
  ports: 
    - name: goserver-service
      port: 80
      targetPort: 80 # if you required a custom container port (CONTAINER_PORT)
      protocol: TCP
      #nodePort: 30001